### ISSUE TITLE
Not so natural...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [renaudcerrato/DoorSignView#1]
If I tilt the device like a Swing (the one for children), I would expect that doing it good enough will also make it perfrom a full rotation.

Using the sample, it feels like it's not the same force. It feels like what I do is putting a strong magnet or something.

**Comment by renaudcerrato** [comment]
This is android widget, not an actual physic simulation. It perfectly fit
our needs at Popsy. BTW, pull requests are welcome.

**Comment by AndroidDeveloperLB** [comment]
Of course.
